### ISSUE TITLE
Unable to Open PO-Summary

### ISSUE THREAD

**Issue by mshahzebraza97** [mshahzebraza97/office-work#7]
### Current Behaviour
Clicking on the `Summary Button` of PO-Entry does not do anything

### Expected Behaviour
A Dialog Box with a summary of purchase detail along with the items purchased should appear.

### Tasks/Features
- [x] Task 1: Troubleshoot and resolve the issue of unresponsive summary-button
- [x] #8
   - logic for all data types to be reviewed for summarizer function (strings, numbers, array, nested-arrays, object) 
   - review, refactor, and write tests for the code of `summarizerNew2`
- [x] Task 3: Ensure that fields with all data types (strings, numbers, array, nested-arrays, object) are displayed properly in summary
- [x] Task 4: Dialog Box is from mui-design-system
- [x] Task 5: Review and refactor the code (if needed)
